### ISSUE TITLE
postRecord throws something went wrong

### ISSUE THREAD

**Issue by seejwy** [broadwayinc/skapi-js#1]
skapi.postRecord({
	'status': 'endangered',
	'price': 30000
}, {
	access_group: 0,
	index: {
		name: 'count',
		value: 1
	},
	table: 'Insects',
	tags: ['FlowerMantis'],
	record_id: 'TP7x5DK9J9B1QO8T',
	service: 'ap22TP6h6dSLezsRQO8T'
})

**Comment by broadwayinc** [comment]
resolved. closing.
